on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-path: ${{ steps.pnpm-cache-path.outputs.store }}
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Get pnpm cache directory path
        id: pnpm-cache-path
        run: |
          echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ steps.pnpm-cache-path.outputs.store }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

      - name: Install packages
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ needs.setup.outputs.pnpm-cache-path }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      - name: lint & format
        run: pnpm lint && pnpm format
      - name: vitest
        run: pnpm vitest
      - name: Playwright tests
        continue-on-error: true
        run: npx playwright install --with-deps && pnpm test:e2e 
      - uses: actions/upload-artifact@v4
        if: '!cancelled()'
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30